### ISSUE TITLE
Debian 10 - not able to start

### ISSUE THREAD

**Issue by Arferol** [Cygn/pulseaudio-dlna#18]
Hi all,
I ask you please for help. I am not able to start pulseaudio-dlna on my Debian 10 system.

This is what it says:
Traceback (most recent call last):
  File "/usr/local/bin/pulseaudio-dlna", line 11, in <module>
    load_entry_point('pulseaudio-dlna==0.6.1', 'console_scripts', 'pulseaudio-dlna')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/pulseaudio_dlna-0.6.1-py3.7.egg/pulseaudio_dlna/__init__.py", line 24, in <module>
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 483, in get_distribution
    raise TypeError("Expected string, Requirement, or Distribution", dist)
TypeError: ('Expected string, Requirement, or Distribution', None)

Any idea please?
Thank you! :)

**Comment by Cygn** [comment]
- this repo is is mainly for rpm packaging, you should head to https://github.com/masmu/pulseaudio-dlna for code issues.
- But I think your issue is a multi-installation one. Make sure that you uninstall all previous versions - check that there is no pulseaudio-dlna* in /usr/lib/python3.7 -  /usr/local/lib/python3.7 and .local/lib/python3.7 etc. `rm -fr` if you find any directory or *.egg.
- Then clone this repo and install with `pip3 install --user .`  
- Note that you'll need pychromecast >= 7.5.1 . You may need to install this also by pip3 if it's not provided by debian.

**Comment by Arferol** [comment]
Thanks 👍 closing issue
