### ISSUE TITLE
Not working with BubbleUPnP

### ISSUE THREAD

**Issue by oxysoft** [Cygn/pulseaudio-dlna#22]
This prints in the logs when I try to switch to the BubbleUPnP renderer (on my phone)

```
09-08 20:54:08 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "BubbleUPnP (moto g(9) play) (DLNA)" to play ...
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pulseaudio_dlna/plugins/dlna/renderer.py", line 93, in play
    stream_url = url or self.get_stream_url()
  File "/usr/lib/python3.9/site-packages/pulseaudio_dlna/plugins/renderer.py", line 350, in get_stream_url
    return self._encode_settings(settings, 'stream.' + self.codec.suffix)
  File "/usr/lib/python3.9/site-packages/pulseaudio_dlna/plugins/renderer.py", line 329, in _encode_settings
    server_ip = pulseaudio_dlna.utils.network.get_host_by_ip(self.ip)
  File "/usr/lib/python3.9/site-packages/pulseaudio_dlna/utils/network.py", line 50, in get_host_by_ip
    return __pyroute2_get_host_by_ip(ip)
  File "/usr/lib/python3.9/site-packages/pulseaudio_dlna/utils/network.py", line 68, in __pyroute2_get_host_by_ip
    ipr = pyroute2.IPRoute()
  File "/home/nuck/.local/lib/python3.9/site-packages/pyroute2/__init__.py", line 26, in _wrapper
    _temp = __import__(_modules[name], globals(), locals(), [name], 0)
  File "/home/nuck/.local/lib/python3.9/site-packages/pyroute2/iproute.py", line 62, in <module>
    from pyroute2.netlink import NLMSG_ERROR
  File "/home/nuck/.local/lib/python3.9/site-packages/pyroute2/netlink/__init__.py", line 333, in <module>
    from pyroute2.common import hexdump
  File "/home/nuck/.local/lib/python3.9/site-packages/pyroute2/common.py", line 20, in <module>
    ANCIENT = (platform.dist()[0] in ('redhat', 'centos') and
AttributeError: module 'platform' has no attribute 'dist'
09-08 20:54:08 pulseaudio_dlna.pulseaudio                     ERROR    The device "BubbleUPnP (moto g(9) play) (DLNA)" failed to play! (500) - Unknown exception.
```

pulseaudio-dlna 0.6.0, installed from aur.

From my searching, it seems my python version is too recent, but what should I do? Virtualenv? How would I use virtualenv to use a different python version? And which version? I'm not too familiar with python ecosystems ...

**Comment by Cygn** [comment]
Hello,
This repo is for packaging for Fedora & co, and not the original dev branch - you should go to https://github.com/masmu/pulseaudio-dlna for proper reporting your issue. I also think that AUR you mentioned follows upstream, not here. 

This being said, python 3.9 compatibility is patched here for fedora, try [ this AUR ](https://aur.archlinux.org/packages/pulseaudio-dlna-python3/) following my branch rather than upstream.
