### ISSUE TITLE
Zeroconf can't connect to port 5353

### ISSUE THREAD

**Issue by leoric** [Cygn/pulseaudio-dlna#26]
when I run pulseaudio-dlna (0.6.2) I get

pulseaudio_dlna.pulseaudio                     INFO     Connecting to pulseaudio on "unix:path=/run/user/1000/pulse/dbus-socket" ...
zeroconf                                       WARNING  Error with socket 24 (('<my ip>', 5353))): [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 1048, in sendto
    self._sock.sendto(data, addr)
PermissionError: [Errno 1] Operation not permitted
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pulseaudio_dlna/plugins/dlna/ssdp/discover.py", line 126, in _send_discover
    sock.sendto(msg, (self.SSDP_ADDRESS, self.SSDP_PORT))
PermissionError: [Errno 1] Operation not permitted

**Comment by Cygn** [comment]
Hello,
not sure that it comes form changes in pulseaudio-dlna. See the latest PR, which is completely unrelated. Does 0.6.1 used to work for you ?

**Comment by leoric** [comment]
issue happened with 0.6.1 too, but I had no reliable way to reproduce, and reboot solved
$ pulseaudio-dlna -v  
0.6.1
$ pulseaudio-dlna
12-14 21:15:56 pulseaudio_dlna.plugins.chromecast             INFO     ChromecastPlugin.discover()
12-14 21:15:56 zeroconf                                       WARNING  Error with socket 20 (('192.168.3.2', 5353))): [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 1048, in sendto
    self._sock.sendto(data, addr)
PermissionError: [Errno 1] Operation not permitted
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/home/leoric/.local/lib/python3.8/site-packages/pulseaudio_dlna/plugins/dlna/ssdp/discover.py", line 126, in _send_discover
    sock.sendto(msg, (self.SSDP_ADDRESS, self.SSDP_PORT))
PermissionError: [Errno 1] Operation not permitted
^CException in thread Thread-6:
Application is shutting down ...
Traceback (most recent call last):
Process Process-3:
12-14 21:15:57 pulseaudio_dlna.pulseaudio                     INFO     PulseWatcher.shutdown()
