### ISSUE TITLE
AttributeError: 'Chromecast' object has no attribute 'cast_info'

### ISSUE THREAD

**Issue by DavidJRobertson** [Cygn/pulseaudio-dlna#39]
When I run pulseaudio-dlna, I get this error:

```
02-27 00:32:01 pychromecast                                   INFO     Querying device status
Exception in thread zeroconf-ServiceBrowser__googlecast._tcp.local.:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/zeroconf/__init__.py", line 1557, in run
    self._service_state_changed.fire(
  File "/usr/lib/python3/dist-packages/zeroconf/__init__.py", line 1333, in fire
    h(**kwargs)
  File "/usr/lib/python3/dist-packages/zeroconf/__init__.py", line 1427, in on_change
    listener.add_service(*args)
  File "/usr/lib/python3/dist-packages/pychromecast/discovery.py", line 65, in add_service
    self._add_update_service(zconf, typ, name, self.add_callback)
  File "/usr/lib/python3/dist-packages/pychromecast/discovery.py", line 123, in _add_update_service
    callback(uuid, name)
  File "/usr/lib/python3/dist-packages/pychromecast/__init__.py", line 246, in internal_callback
    callback(
  File "/home/david/.local/lib/python3.9/site-packages/pulseaudio_dlna/plugins/__init__.py", line 36, in wrapper
    device = f(*args, **kwargs)
  File "/home/david/.local/lib/python3.9/site-packages/pulseaudio_dlna/plugins/chromecast/__init__.py", line 47, in _on_device_added
    return ChromecastRendererFactory.from_pychromecast(device)
  File "/home/david/.local/lib/python3.9/site-packages/pulseaudio_dlna/plugins/chromecast/renderer.py", line 191, in from_pychromecast
    manufacturer=pychromecast.cast_info.manufacturer,
AttributeError: 'Chromecast' object has no attribute 'cast_info'
```

My google nest mini speakers do not show up in the list of outputs. Following the pychromecast examples, they do work.
Pychromecast version is 7.7.1.

**Comment by DavidJRobertson** [comment]
It appears to work when I use PyChromecast==10.2.3. The version requirement in setup.py should be updated.

**Comment by Cygn** [comment]
Should be fixed in 0.6.4 - have you tried that ?

**Comment by tomerrr** [comment]
i'm having the same problem on Fedora 34 since upgraded to pulseaudio-dlna 0.6.4-1 . 
Python-chromecast is python3-chromecast-9.2.0-1.fc34.noarch
workaround: remove pulseaudio-dlna with dnf
install PyChromecast with pip (sudo pip install PyChromecast)
and install pulseaudio-dlna again . tested on Fedora 34 & 35

**Comment by Cygn** [comment]
I've just packaged pychromecast=10.3 and published on COPR - that should correct the issue.

**Comment by tomerrr** [comment]
when trying to update package on Fedora 35 I get
```
Problem 1: cannot install the best update candidate for package python3-chromecast-9.3.1-1.fc35.noarch
  - nothing provides python3.10dist(protobuf) >= 3.19.1 needed by python3-chromecast-10.3.0-2.noarch
 Problem 2: package pulseaudio-dlna-0.6.5-1.noarch requires python3.10dist(pychromecast) >= 10, but none of the providers can be installed
  - cannot install the best update candidate for package pulseaudio-dlna-0.6.4-1.noarch
  - nothing provides python3.10dist(protobuf) >= 3.19.1 needed by python3-chromecast-10.3.0-2.noarch

```
