### ISSUE TITLE
Failure when trying to create null sink: TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by blueyed** [Cygn/pulseaudio-dlna#46]
I am getting this error:
```
06-29 17:10:23 pulseaudio_dlna.plugins.chromecast             INFO     ChromecastPlugin.discover()
Failure: Module initialization failed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gi/overrides/GLib.py", line 671, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "…/Vcs/pulseaudio-dlna/pulseaudio_dlna/pulseaudio.py", line 641, in _on_new_message
    getattr(self, message_type)(**message)
  File "…/Vcs/pulseaudio-dlna/pulseaudio_dlna/pulseaudio.py", line 835, in add_device
    sink = self.create_null_sink(
  File "…/Vcs/pulseaudio-dlna/pulseaudio_dlna/pulseaudio.py", line 268, in create_null_sink
    if module_id > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

Code ref: https://github.com/masmu/pulseaudio-dlna/blob/25e7c21b1bbe51fe4ef68ef5ded126c3424ccd30/pulseaudio_dlna/pulseaudio.py#L242-L268

This can easily be fixed by checking for None there, but it also appears to be wrong that creating the sink fails for all the cast devices I have.
The cmd is e.g. `pactl load-module module-null-sink sink_name="tv_chromecast" sink_properties=device.description="TV\\ (Chromecast)"`.

With the following patch it does not crash, but also does not the sinks also:
```diff
diff --git i/pulseaudio_dlna/pulseaudio.py w/pulseaudio_dlna/pulseaudio.py
index 5960a40..4c5382b 100644
--- i/pulseaudio_dlna/pulseaudio.py
+++ w/pulseaudio_dlna/pulseaudio.py
@@ -265,7 +265,7 @@ def create_null_sink(self, sink_name, sink_description):
                 sink_description.replace(' ', '\ ')),)
         ])
         module_id = self.load_module(MODULE_NULL_SINK, options)
-        if module_id > 0:
+        if module_id is not None:
             self.update_sinks()
             for sink in self.sinks:
                 if int(sink.module.index) == module_id:
```

Also it should not display a success message then also obviously:
```
06-29 17:31:58 pulseaudio_dlna.plugins.chromecast             INFO     ChromecastPlugin.discover()
Failure: Module initialization failed
06-29 17:31:58 pulseaudio_dlna.pulseaudio                     INFO     Added the device "Nest Audio Foo (Chromecast)".
```

FWIW, `pactl load-module module-null-sink sink_name=foo` fails by itself already, so it is likely a problem with pulseaudio itself, but should get handled better with/by pulseaudio-dlna.

**Comment by Cygn** [comment]
This branch does not work on pipewire without fidgeting. You may try https://github.com/EvTheFuture/pulseaudio-dlna/tree/testing_with_pipewire to see if this works for you.
